version: '3.9'

services:
  php:
    build:
      context: docker/php
    volumes:
      - ./:/srv/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  meilisearch:
    image: getmeili/meilisearch:v1.4
    environment:
      MEILI_ENV: ${MEILI_ENV:-development}
      MEILI_LOG_LEVEL: ${MEILI_LOG_LEVEL:-INFO}
      MEILI_NO_ANALYTICS: true
    volumes:
      - './docker/meili/data.ms:/data.ms'
