version: '3.7'

services:
  php:
    build:
      context: docker/php
    volumes:
      - ./:/srv/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  meili:
    image: getmeili/meilisearch
    volumes:
      - './docker/meili/data.ms:/data.ms'
