name: MeiliSearchBundle CI - Config
on: [ push ]
jobs:
  meili_configuration:
    name: Configuration
    # https://hub.docker.com/_/ubuntu/
    runs-on: ubuntu-18.04
    steps:
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/azohra/shell-linter (community)
      - name: Lint check
        uses: azohra/shell-linter@v0.3.0
        with:
          path: "docker/php"
