name: MeiliSearchBundle CI

on:
  push:
    branches:
      - master

jobs:
  meili_search:
    name: PHP ${{ matrix.php-versions }} - ${{ matrix.composer-dependencies }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions:
          - '8.1'
          - '8.2'
        composer-dependencies: ['', 'lowest']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: zip, xdebug
          coverage: xdebug
        env:
          update: true

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get composer cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.composer-dependencies }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-${{ matrix.composer-dependencies }}-

      - name: Install Composer dependencies
        if: matrix.composer-dependencies == ''
        run: composer update

      - name: Install Composer dependencies - Lowest
        if: matrix.composer-dependencies == 'lowest'
        run: composer update --prefer-lowest
