name: Shell Linter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  shell_linter:
    name: Shell Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint check
        uses: azohra/shell-linter@v0.6.0
        with:
          path: "docker/php"
